# Generated by Django 3.0.3 on 2020-03-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='profit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='sellingprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sold_products',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sold_products',
            name='sellingprice',
            field=models.IntegerField(),
        ),
    ]
