# Generated by Django 3.0.3 on 2020-03-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Inventory', '0002_auto_20200308_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='empusername',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
